### ISSUE TITLE
Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`

### ISSUE THREAD

**Issue by alterx** [ayushnawani/react-native-alphabetflatlist#4]
It seems like the wrong type is being used here as `CellRenderer` expects a `string` but a `number` is being sent instead. I've been able to track the issue down to line 161 of `index.js` (https://github.com/ayushnawani/react-native-alphabetflatlist/blob/master/index.js#L161)

This error applies for the right side Alphabet FlatList `keyExtractor` so it can't be overwritten. It looks like there are two options to fix this:

1) Instead of using 
```
alphabetKeyExtractor = (item, index) => index
```
we could use
```
alphabetKeyExtractor = (item, index) => index.toString()
```
2) Allow people to overwrite the the Alphabet Flatlist `keyExtractor`.

I think it makes more sense to apply fix # 1 since the right side Alphabet FlatList is controlled, mainly, by the library.

What are your thoughts on this?

**Comment by ayushnawani** [comment]
@alterx  I have released new version 1.0.5 with the changes, can you check it?

**Comment by alterx** [comment]
@ayushnawani , confirmed, the warning is gone :D 

Thanks for the quick response!

**Comment by ayushnawani** [comment]
@alterx  that's great. thanks for confirming.
